### PR TITLE
Mkdocs build fix and install instructions

### PR DESCRIPTION
**Pull request by aristizabal95**
This PR addresses a hidden bug that caused mkdocs to fail at build/serve time. This was caused by a build param that was updated some time ago.

Additionally, this PR includes a `requirements.txt` file and instructions for running mkdocs locally, for documentation contributions.

### CODE REVIEW

**Review by hasan7n — CHANGES_REQUESTED** [review]
It's great having the instructions!

**In brief:**
github workflow building the docs should fail now. We should revert back the change in `gen_ref_pages.py` and 'correctly' install mkdocs requirements, which are listed in `docs-ci.yml`, to have successful local serving. Let me know if I am missing something.

**Long answer:**

https://github.com/mlcommons/medperf/blob/a39b84143cdcc39016a7f12ce30b82c9687f4210/docs/gen_ref_pages.py#L12

Regarding the above change, I remember I did that for the GitHub workflow `.github/docs-ci.yml`. After this PR, local serving works but github workflow will fail (tested on my fork). Can you confirm?

It seems that this is a problem of requirements. If we locally install the following as stated in `docs-ci.yml`:
`pip install mkdocs-material mkdocstrings[python] mkdocs-gen-files mkdocs-literate-nav`
Local serving will work fine.

So we have two options:
1. update docs-ci.yml to install the listed requirements in this PR
2. revert back the change in `gen_ref_pages.py`, and modify the requirements.txt to contain what the current docs-ci.yml contains.

I would go with 2. since I noticed locally that latest versions of mkdocs libraries (not sure which one) give rich warnings when docstrings don't resemble function signatures.


+ to remember: going with 1. requires a small change to hide tests from documentation

Let me know what you think. I can do the changes but want you to confirm-test if local serving will work if we used only the requirements listed in `docs-ci.yml` (which works for me in pythons 3.7 and 3.10).

**Comment by hasan7n** [comment]
by the way, do you think it would be good if we add a new check for pull requests to test if `mkdocs build` works?

**Comment by aristizabal95** [comment]
Hey Hasan, thanks for the explanation! I was sure there was a reason behind the `cli/medperf` that I was removing. I totally agree that we should stick with the steps provided within `docs-ci.yml`. I tried doing the local installation with those packages, but I'm not able to run `mkdocs serve`. `jinja2==3.0.0` seems to be required, but even then I get errors like `ERROR    -  Could not collect 'config'` which I don't get when using the `requirements.txt` provided on this PR. I think we should look into this to discover the discrepancy, so we can modify this PR accordingly.

**Review by hasan7n — APPROVED** [review]
It works both locally and on Github!

**Pull request merged**
