### PR TITLE
Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by aristizabal95**
This PR combines all suggestions from dependabot to fix dsicovered vulnerabilities in PyYAML and Django

### CODE REVIEW

**Comment by johnugeorge** [comment]
this has version dependency with mlcube?

**Review by msheller — APPROVED** [review]
Thanks, Alejandro!

**Comment by aristizabal95** [comment]
> this has version dependency with mlcube?

We could remove it and instead ask users to install it manually beforehand

**Comment by johnugeorge** [comment]
> > this has version dependency with mlcube?
> 
> We could remove it and instead ask users to install it manually beforehand

But, users would get conflict when try to install ?  We should ask MLCube team to update their package

**Comment by aristizabal95** [comment]
> > > this has version dependency with mlcube?
> > 
> > 
> > We could remove it and instead ask users to install it manually beforehand
> 
> But, users would get conflict when try to install ? We should ask MLCube team to update their package

Agreed, I just asked Jurado. I guess we'll have to wait until they release a new update

**Comment by aristizabal95** [comment]
That was faster than expected!

**Pull request merged**
