### PR TITLE
Adaptation of BraTS cubes for FeTS challenge

### PR DESCRIPTION
**Pull request by mzenk**
This is a first commit towards adapting the BraTS example for the FeTS challenge. It's in draft form still because we need to clarify where to store the final version for FeTS.
Additions:
- Add true positive counts etc. to the results.yaml
- Add basic logging
Modifications:
- Data folder (names) conventions
Could you review these @sarthakpati ?

One thing that's not clear to me is: why is the python version not 3.8 as it looks like in the Dockerfile? Could need help from @sarthakpati to debug this (although the installed version 3.6.4 is ok, too).

### CODE REVIEW

**Comment by aristizabal95** [comment]
Hi @mzenk, thanks for helping out with this. A few notes from what I've been able to test:

- It appears that CentOS doesn't have python3.8 ready to install. Instead, it must be built from source. 
  ```
  [root@dbfd3576f2a4 project]# yum install python3.8 python3-pip -y
  Loaded plugins: fastestmirror, ovl
  Loading mirror speeds from cached hostfile
   * base: mirror.ci.ifes.edu.br
   * centos-sclo-rh: mirror.ci.ifes.edu.br
   * centos-sclo-sclo: mirror.ci.ifes.edu.br
   * extras: mirror.ci.ifes.edu.br
   * updates: mirror.ci.ifes.edu.br
  No package python3.8 available.
  Package python3-pip-9.0.3-8.el7.noarch already installed and latest version
  Nothing to do
  ```
  https://computingforgeeks.com/how-to-install-python-3-on-centos/
  If python3.8 is not strictly necessary then I would stay with 3.6
- The results generated by the evaluator mlcube don't look as expected. For comparison, here are the results from the Alpha Test version vs the current implementation:
  __Alpha Test Results__
  ```
  Case1:
    Dice_ET: 0.732883
    Dice_TC: 0.845585
    Dice_WT: 0.905164
    Hausdorff95_ET: 2.44949
    Hausdorff95_TC: 7.0
    Hausdorff95_WT: 3.316625
    Precision_ET: 0.9421790000000001
    Precision_TC: 0.914223
    Precision_WT: 0.8416
    Sensitivity_ET: 0.599671
    Sensitivity_TC: 0.7865340000000001
    Sensitivity_WT: 0.979115
    Specificity_ET: 0.999925
    Specificity_TC: 0.9998299999999999
    Specificity_WT: 0.998491
  Case2:
    Dice_ET: 0.8638319999999999
    Dice_TC: 0.139572
    Dice_WT: 0.8992979999999999
    Hausdorff95_ET: 2.0
    Hausdorff95_TC: 20.024984
    Hausdorff95_WT: 4.123106
    Precision_ET: 0.94958
    Precision_TC: 0.993367
    Precision_WT: 0.933218
    Sensitivity_ET: 0.792287
    Sensitivity_TC: 0.075059
    Sensitivity_WT: 0.867757
    Specificity_ET: 0.9999950000000001
    Specificity_TC: 0.9999979999999999
    Specificity_WT: 0.9996459999999999
  config.yaml:
    Dice_ET: 0.0
    Dice_TC: 0.0
    Dice_WT: 0.0
    Hausdorff95_ET: 374.0
    Hausdorff95_TC: 374.0
    Hausdorff95_WT: 374.0
    Precision_ET: 0.0
    Precision_TC: 0.0
    Precision_WT: 0.0
    Sensitivity_ET: 0.0
    Sensitivity_TC: 0.0
    Sensitivity_WT: 0.0
    Specificity_ET: 0.0
    Specificity_TC: 0.0
    Specificity_WT: 0.0
  ```
  __Current Implementation__
  ```
  Case1:
    Dice_ET: 0
    Dice_TC: 0
    Dice_WT: 0
    FN_ET: 8928000
    FN_TC: 8928000
    FN_WT: 8928000
    FP_ET: 0
    FP_TC: 0
    FP_WT: 0
    Hausdorff95_ET: 374
    Hausdorff95_TC: 374
    Hausdorff95_WT: 374
    Precision_ET: 0
    Precision_TC: 0
    Precision_WT: 0
    Sensitivity_ET: 0
    Sensitivity_TC: 0
    Sensitivity_WT: 0
    Specificity_ET: 0
    Specificity_TC: 0
    Specificity_WT: 0
    TN_ET: 0
    TN_TC: 0
    TN_WT: 0
    TP_ET: 0
    TP_TC: 0
    TP_WT: 0
  Case2:
    Dice_ET: 0
    Dice_TC: 0
    Dice_WT: 0
    FN_ET: 8928000
    FN_TC: 8928000
    FN_WT: 8928000
    FP_ET: 0
    FP_TC: 0
    FP_WT: 0
    Hausdorff95_ET: 374
    Hausdorff95_TC: 374
    Hausdorff95_WT: 374
    Precision_ET: 0
    Precision_TC: 0
    Precision_WT: 0
    Sensitivity_ET: 0
    Sensitivity_TC: 0
    Sensitivity_WT: 0
    Specificity_ET: 0
    Specificity_TC: 0
    Specificity_WT: 0
    TN_ET: 0
    TN_TC: 0
    TN_WT: 0
    TP_ET: 0
    TP_TC: 0
    TP_WT: 0
  ```
  My gut feeling is that it has something to do with the fact that the alpha test mlcube had the `config.yaml` file which provided the name of the model. I'm aware that this is not possible for the FeTS challenge, but maybe there's something else that needs to be done for the evaluator cube to output working results. @sarthakpati this has more to do with the FeTS tool being used. Do you have any idea of what might be happening?
- The additional output parameter added to the `evaluate` task appears to work, but it doesn't get stored in an independent file for each run (contrary to the `results.yaml` file). This is because medperf doesn't expect more outputs to be there. Every subsequent run will overwrite the previous logs. This isn't necessarily a problem, but something to keep in mind. We can still access the log file and get logs from the latest run.

**Comment by aristizabal95** [comment]
I would also recommend changing the name of the image, or indicating a version so that it doesn't collide with the already existing `mlcommons/fets_metrics` image.

**Comment by mzenk** [comment]
I think the reason why [earlier results are not reproducible](https://github.com/mlcommons/medperf/pull/148#issuecomment-1132238626) is that the output format ist slightly different. Predictions are assumed to be in `/output_path/ID1.nii.gz` etc. while earlier there was a sub-folder for each subject which contained only one nifti file. The model cube currently developed by Jurado and myself should be compatible with the new output format. As this concerns the interface between model cube and evaluation cube, we just have to define it consistently, I think.

**Comment by mzenk** [comment]
As for the other points:
- python 3.6 should be ok
- log files are overwritten: Ok, good to know. Maybe something to change in the future, but for now we can copy the logs somewhere else if we need to, I guess?

**Comment by aristizabal95** [comment]
Ah that makes sense. Let me know when the model MLCube is ready so I can test it with medperf.
Yes, logs can be copied somewhere else in between executions for now. I'll look into allowing multiple outputs to be directed to the results folder for each execution so they're not accidentaly lost/overwritten.

**Review by aristizabal95 — COMMENTED** [review]
Implementation looks great! The data preparation MLCube is correctly using the separate labels path and medperf handles the whole pipeline correctly. There's only one I would mention:

The BraTS models implemented here still return malformed results:
```
FeTS2022_00311:
  Dice_ET: 0
  Dice_TC: 0
  Dice_WT: 0
  FN_ET: 8928000
  FN_TC: 8928000
  FN_WT: 8928000
  FP_ET: 0
  FP_TC: 0
  FP_WT: 0
  Hausdorff95_ET: 374
  Hausdorff95_TC: 374
  Hausdorff95_WT: 374
  Precision_ET: 0
  Precision_TC: 0
  Precision_WT: 0
  Sensitivity_ET: 0
  Sensitivity_TC: 0
  Sensitivity_WT: 0
  Specificity_ET: 0
  Specificity_TC: 0
  Specificity_WT: 0
  TN_ET: 0
  TN_TC: 0
  TN_WT: 0
  TP_ET: 0
  TP_TC: 0
  TP_WT: 0
FeTS2022_00805:
  Dice_ET: 0
  Dice_TC: 0
  Dice_WT: 0
  FN_ET: 8928000
  FN_TC: 8928000
  FN_WT: 8928000
  FP_ET: 0
  FP_TC: 0
  FP_WT: 0
  Hausdorff95_ET: 374
  Hausdorff95_TC: 374
  Hausdorff95_WT: 374
  Precision_ET: 0
  Precision_TC: 0
  Precision_WT: 0
  Sensitivity_ET: 0
  Sensitivity_TC: 0
  Sensitivity_WT: 0
  Specificity_ET: 0
  Specificity_TC: 0
  Specificity_WT: 0
  TN_ET: 0
  TN_TC: 0
  TN_WT: 0
  TP_ET: 0
  TP_TC: 0
  TP_WT: 0
FeTS2022_01151:
  Dice_ET: 0
  Dice_TC: 0
  Dice_WT: 0
  FN_ET: 8928000
  FN_TC: 8928000
  FN_WT: 8928000
  FP_ET: 0
  FP_TC: 0
  FP_WT: 0
  Hausdorff95_ET: 374
  Hausdorff95_TC: 374
  Hausdorff95_WT: 374
  Precision_ET: 0
  Precision_TC: 0
  Precision_WT: 0
  Sensitivity_ET: 0
  Sensitivity_TC: 0
  Sensitivity_WT: 0
  Specificity_ET: 0
  Specificity_TC: 0
  Specificity_WT: 0
  TN_ET: 0
  TN_TC: 0
  TN_WT: 0
  TP_ET: 0
  TP_TC: 0
  TP_WT: 0
```
This is probably because this models are outdated given the latest changes in the data preparation and evaluator mlcube, but I want to make sure this is expected. In case it helps, these are the folder structures generated by each mlcube:

Data Preparator Output
```
/Users/aristizabal-factored/.medperf/data/test_cf7f2dfb8a26f75b46bf99c7f470f2b65dd5e924/
├── data
│   ├── FeTS2022_00311
│   │   ├── FeTS2022_00311_brain_flair.nii.gz
│   │   ├── FeTS2022_00311_brain_t1.nii.gz
│   │   ├── FeTS2022_00311_brain_t1ce.nii.gz
│   │   └── FeTS2022_00311_brain_t2.nii.gz
│   ├── FeTS2022_00805
│   │   ├── FeTS2022_00805_brain_flair.nii.gz
│   │   ├── FeTS2022_00805_brain_t1.nii.gz
│   │   ├── FeTS2022_00805_brain_t1ce.nii.gz
│   │   └── FeTS2022_00805_brain_t2.nii.gz
│   └── FeTS2022_01151
│       ├── FeTS2022_01151_brain_flair.nii.gz
│       ├── FeTS2022_01151_brain_t1.nii.gz
│       ├── FeTS2022_01151_brain_t1ce.nii.gz
│       └── FeTS2022_01151_brain_t2.nii.gz
├── labels
│   ├── FeTS2022_00311_final_seg.nii.gz
│   ├── FeTS2022_00805_final_seg.nii.gz
│   └── FeTS2022_01151_final_seg.nii.gz
└── registration-info.yaml
```

Model Output
```
~/.medperf/predictions/2/test_cf7f2dfb8a26f75b46bf99c7f470f2b65dd5e924/
├── FeTS2022_00311
│   ├── FeTS2022_00311_brain_flair.nii.gz
│   ├── FeTS2022_00311_brain_t1.nii.gz
│   ├── FeTS2022_00311_brain_t1ce.nii.gz
│   ├── FeTS2022_00311_brain_t2.nii.gz
│   ├── FeTS2022_00311_deepmedic_seg.nii.gz
│   ├── FeTS2022_00311_fused_staple_seg.nii.gz
│   └── SegmentationsForQC
├── FeTS2022_00805
│   ├── FeTS2022_00805_brain_flair.nii.gz
│   ├── FeTS2022_00805_brain_t1.nii.gz
│   ├── FeTS2022_00805_brain_t1ce.nii.gz
│   ├── FeTS2022_00805_brain_t2.nii.gz
│   ├── FeTS2022_00805_deepmedic_seg.nii.gz
│   ├── FeTS2022_00805_fused_staple_seg.nii.gz
│   └── SegmentationsForQC
├── FeTS2022_01151
│   ├── FeTS2022_01151_brain_flair.nii.gz
│   ├── FeTS2022_01151_brain_t1.nii.gz
│   ├── FeTS2022_01151_brain_t1ce.nii.gz
│   ├── FeTS2022_01151_brain_t2.nii.gz
│   ├── FeTS2022_01151_deepmedic_seg.nii.gz
│   ├── FeTS2022_01151_fused_staple_seg.nii.gz
│   └── SegmentationsForQC
└── config.yaml
```

Evaluator Output
```
~/.medperf/results/tmp_1_2_3/2/test_cf7f2dfb8a26f75b46bf99c7f470f2b65dd5e924
└── result.yaml
```

The evaluator MLCube generated logs, but the Data Preparator MLCube didn't. Is this also expected?

**Comment by mzenk** [comment]
Thanks for your feedback! Indeed, the "old" model cubes are not compatible with the current naming conventions. This is ok for now, because we provide a template with compatible output formatting.

**Comment by mzenk** [comment]
Closing this, as we move the example to the [official challenge repo](https://github.com/FETS-AI/Challenge/tree/main/Task_2) for now

**Pull request closed without merging**
