### PR TITLE
Implement Data Preparation logic for manual steps

### LINKED ISSUE #506: [FEATURE] Implement Data Preparation logic for manual steps
Details in the linked pull request

### PR DESCRIPTION
**Pull request by aristizabal95**
This PR adds the required logic for handling Data Preparation workflows where manual steps are needed in between. This is done by storing not-yet-prepared datasets in a staging folder, and allowing the user to resume preparation by using the same dataset name. Datasets now also create a report file containing information about the execution, and medperf automatically generates a summary for the user to determine what to do in case of errors or manual steps.
Closes #506

### CODE REVIEW

**Comment by hasan7n** [comment]
@aristizabal95 

QUESTION: do we need input dataset hash to be editable as well? or Did we decide on the fact that users should edit the staging folder if they want to modify the input data? (e.g. remove a subject)

Here is a summary of the server changes:

**Report entity fields**
```
    dataset_name (str) required
    input_data_hash (str) required
    data_preparation_mlcube (int) required
    benchmark (int) required
    contents (dict) default is {}

    description (str)  default is ""
    location (str)  default is ""

    is_valid (bool) default is True

    metadata (dict) default is {}
    user_metadata (dict) default is {}
    
    created_at, modified_at, owner: auto-generared by the server
``` 

**Editable fields**
`metadata, user_metadata, contents, is_valid`

**Endpoints**
`POST /reports`: Any user is allowed
`GET /reports`: nobody is allowed (only admin)

`GET /benchmarks/<benchmark_id>/reports`: Only benchmark owner

`GET /reports/<report_id>`: benchmark owner, report owner, and data prep MLCube owner are allowed.
`PUT /reports/<report_id>`: only report owner is allowed.
`DELETE /reports/<report_id>`: nobody (only admin)

**Comment by aristizabal95** [comment]
@hasan7n We decided on users being able to edit the input folder as well, so the input data hash should be editable! Thanks for all your help!

**Comment by hasan7n** [comment]
Fixes #488

**Comment by hasan7n** [comment]
TODO: we need to modify report submission sigint handler after merging #523

**Review by hasan7n — APPROVED** [review]

**Pull request merged**
