### PR TITLE
[feat] Upgrade synapseclient version; update `synapse_login` command

### LINKED ISSUE #474: [FEATURE] Update Synapse login to only use `authToken`
**Is your feature request related to a problem? Please describe.**
The Synapse Python Client has [plans to deprecate](https://python-docs.synapse.org/build/html/news.html) non-auth token logins (e.g. username + password) as well as the `rememberMe` parameter by early 2024.

**Describe the solution you'd like**
Remove the option to log in with a username and password:

Screenshot 2023-08-03 at 10 33 10 AM

as well as remove all instances of the `rememberMe` parameter in `syn.login()`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #474

## Changelog
* Upgrade synapseclient to v4.1.1
* Remove deprecated login option with username + password
* Remove deprecated login parameter: `rememberMe`
* Update UI prompt message (and include a link to generating a Synapse PAT)
* Use `raise from` for exception chaining
* Update unit tests

## Preview

**Before update**

```text
$  medperf auth synapse_login
MedPerf 0.1.0
How do you want to login?
[1] Personal Access Token
[2] Username and Password
Select an option (1 or 2): 1
access token: 

UPGRADE AVAILABLE

A more recent version of the Synapse Client (4.1.1) is available. Your version (2.7.0) can be upgraded by typing:
    pip install --upgrade synapseclient

Python Synapse Client version 4.1.1 release notes

https://python-docs.synapse.org/news/

Welcome, Verena Chung!

✅ Done!
```

**After update**

```text
$ medperf auth synapse_login
MedPerf 0.1.0
Please provide your Synapse Personal Access Token (PAT). You can generate a new PAT at https://www.synapse.org/#!PersonalAccessTokens:0
Synapse PAT: 
Welcome, Verena Chung!

✅ Done!
```

```text
$ medperf auth synapse_login --token ...
MedPerf 0.1.0
Welcome, Verena Chung!

✅ Done!
```

## Unit test results

```python
$ pytest cli/medperf/tests/commands/auth/test_synapse_login.py 
============================================= test session starts ==============================================
platform darwin -- Python 3.9.17, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/vchung/Desktop/medperf/cli
plugins: mock-1.13.0, pyfakefs-5.0.0, time-machine-2.4.0
collected 3 items                                                                                              

cli/medperf/tests/commands/auth/test_synapse_login.py ...                                                [100%]

============================================== 3 passed in 2.26s ===============================================
```

### CODE REVIEW

**Comment by vpchung** [comment]
@hasan7n please let me know if there are particular tests I need to run for this feature request.  Thanks!

**Comment by hasan7n** [comment]
Thanks @vpchung for the changes and the very well-documented PR!
Everything looks good except some linting errors then this can be merged.

**Comment by vpchung** [comment]
@hasan7n will do!  Which linter does the medperf project follow?

**Comment by hasan7n** [comment]
Thanks! It seems there are some tests unit tests failing

btw this is how MedPerf lints using flake8: https://github.com/mlcommons/medperf/actions/runs/8365130044/workflow?pr=559#L30-L37

**Comment by vpchung** [comment]
Thanks! I was looking for unit tests to update but couldn't find them (clearly did not look hard enough 😅).  I will address these now.

**Review by hasan7n — APPROVED** [review]
Thanks Verena!

**Pull request merged**
